;; LUKAS' EMACS CONFIG

;; This must come before configurations of
;; installed packages.  Don't delete this line.
(package-initialize)

;; Enable mouse interactivity (scrolling, etc)
(xterm-mouse-mode 1)

;; Set default tab width to 4 unless specified otherwise in a language mode
;; specific hook
(setq c-basic-offset 4)

;; Enable having line numbers appear on the LHS of the buffer
(global-linum-mode t)

;; Manually set theme path and load theme example
;; (add-to-list 'custom-theme-load-path "/home/lukas/.emacs.d/themes/")
;; (load-theme 'cyberpunk t)

;; Set font size:
;; 10pt = 100, 12pt = 120, etc.
;; Here, I set the font size to 13pt.
;; Note: This actually is overwritten by custom-set-faces later.
;; I have kept it here as an example.
(set-face-attribute 'default nil :height 130)

;; Make cursor a normal ide cursor
(setq-default cursor-type 'bar)

;; Set cursor color
(set-cursor-color "#d742f4")

;; Make system copy and paste work with emacs copy and paste
;; (Necessary to be able to copy and paste in and out of emacs from
;; other applications)
(setq x-select-enable-clipboard t)

;; Set neotree extension to execute by pressing the f8 key
(global-set-key [f8] 'neotree-toggle)

;; Add melpa packages to package-list-packages
(require 'package)
(add-to-list 'package-archives
       '("melpa" . "http://melpa.milkbox.net/packages/"))

;; Enable smooth scrolling (default emacs scrolling sucks)
(require 'smooth-scrolling)
(smooth-scrolling-mode 1)

;; Autocomplete go code
;(require 'go-autocomplete)
;(require 'auto-complete-config)
;(ac-config-default)
;(add-hook 'completion-at-point-functions 'go-complete-at-point)

;; Nick's CMPT 315 addons
(setq gofmt-command "goimports")
(add-hook 'before-save-hook 'gofmt-before-save)


;; Custom-set-variables and custom-set faces are both
;; autogenerated from changing settings and installing packages
;; within emacs itself. Don't edit this code.
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.

 ;; Only enable theme if in GUI mode
 (when (display-graphic-p)
 '(custom-enabled-themes (quote (doom-dracula))))
 '(custom-safe-themes
   (quote
    ("f0dc4ddca147f3c7b1c7397141b888562a48d9888f1595d69572db73be99a024" default)))
 '(inhibit-startup-buffer-menu t)
 '(inhibit-startup-screen t)
 '(package-selected-packages
   (quote
    (smooth-scrolling go-complete go-mode restart-emacs org-journal helm-youtube chess doom-themes restclient neotree))))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:family "Hack" :foundry "SRC" :slant normal :weight normal :height 120 :width normal)))))
